name: Deploy Actions

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Server Mainnet
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SSH_KEY_MAINNET }}
        host: ${{ secrets.SSH_HOST_MAINNET }}
        username: ${{ secrets.SSH_USER_MAINNET }}
        script: pm2 deploy ecosystem.config.js scheduler update
