name: Deploy Actions

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.SSH_KEY }}
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        script: ls
